
spring :

  datasource:
    url: jdbc:postgresql://localhost:5432/MusicAppDemo
    username: postgres
    password: 2446
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    sql:
      init:
        platform: postgres

  thymeleaf:
    enabled: false


